version: 3

tasks:
  docs:
    dir: web
    cmds:
    - pnpm start
  
  docs:build:
    dir: web
    cmds:
    - pnpm install
    - pnpm build

  helm-package-index:
    desc: Package Helm charts and update repository index
    cmds:
    - echo "Adding required Helm repositories..."
    - helm repo add grafana https://grafana.github.io/helm-charts || true
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
    - helm repo update
    - echo "Updating chart dependencies..."
    - helm dependency update helm/loki-stack
    - echo "Creating charts directory..."
    - mkdir -p web/static/charts
    - echo "Cleaning old chart packages..."
    - rm -f web/static/charts/component-chart-*.tgz
    - rm -f web/static/charts/loki-stack-*.tgz
    - echo "Packaging component-chart..."
    - helm package helm/component-chart -d web/static/charts/
    - echo "Packaging loki-stack..."
    - helm package helm/loki-stack -d web/static/charts/
    - echo "Updating Helm repository index..."
    - helm repo index web/static/charts --url https://rishang.github.io/common-chart/charts
    - echo "✅ Charts packaged successfully!"
    - echo "📦 Files created in web/static/charts/"
    - ls -lh web/static/charts/

