apiVersion: v2
name: component-chart
description: A general purpose helm chart for deploying components of an application. [DOCS - https://rishang.github.io/helm-chart/component-chart/introduction]
icon: https://rishang.github.io/helm-chart/img/component-chart-icon.png

version: 0.0.1
