/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  componentChartSidebar: [
    'introduction',
    'usage',
    'reference',
    'examples',
    {
      type: 'category',
      label: 'Configuration',
      items: [{ type: 'autogenerated', dirName: 'configuration' }],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    // Intentionally not listing `fragments/` (these are imported by other MDX pages).
  ],
};


